import {
  Crown,
  Gem,
  Package,
  Footprints,
  Shield,
  Smile,
  UserRound,
  Eye,
  Droplet,
  Sun,
  Sparkles,
  ShieldCheck,
  Syringe,
  Moon,
  Leaf,
  Heart,
  Cookie,
  Mountain,
  Wind,
  CircleDot,
  ArrowUp,
  Activity,
  Aperture,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  crown: Crown,
  gem: Gem,
  package: Package,
  footprints: Footprints,
  shield: Shield,
  smile: Smile,
  "user-round": UserRound,
  eye: Eye,
  droplet: Droplet,
  sun: Sun,
  sparkles: Sparkles,
  "shield-check": ShieldCheck,
  syringe: Syringe,
  moon: Moon,
  leaf: Leaf,
  heart: Heart,
  cookie: Cookie,
  mountain: Mountain,
  wind: Wind,
  "circle-dot": CircleDot,
  "arrow-up": ArrowUp,
  activity: Activity,
  aperture: Aperture,
  waves: Waves,
  zap: Zap,
};

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Sparkles;
}
